version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local:1.12.0
    command: -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb
    ports:
      - "8000:8000"
    restart: always

  dynamodb-manager:
    image: taydy/dynamodb-manager:latest
    ports:
      - "8080:80"
    privileged: true
    restart: always