apiVersion: v2
name: apm-stack
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: apm-server
    version: 7.8.1
    repository: https://helm.elastic.co
    condition: apm-server.enabled
  - name: elasticsearch
    version: 7.8.1
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: kibana
    version: 7.8.1
    repository: https://helm.elastic.co
    condition: kibana.enabled