global:
  secrets:
    elasticsearch:
      name: elasticsearch-password
      username: elastic
      password: 'a123123'
    kibana:
      encryptionKey: aK1CHDTA6lPC57iYtl7hFdfBYke9k4he

apm-server:
  enabled: true
  replicas: 1
  apmConfig:
    apm-server.yml: |
      apm-server:
        host: "0.0.0.0:8200"
      queue: {}
      output.elasticsearch:
        username: '${ELASTICSEARCH_USERNAME}'
        password: '${ELASTICSEARCH_PASSWORD}'
        protocol: https
        hosts: ["https://elasticsearch-master.app.svc.cluster.local:9200"]
        ssl.certificate_authorities:
          - /usr/share/apm-server/config/certs/ca/ca.crt
  extraEnvs:
    - name: ELASTICSEARCH_USERNAME
      valueFrom:
        secretKeyRef:
          name: elasticsearch-password
          key: username
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elasticsearch-password
          key: password
  secretMounts:
    - name: ca-keys
      secretName: ca-keys
      path: /usr/share/apm-server/config/certs/ca

elasticsearch:
  enabled: true
  replicas: 1
  esJavaOpts: '-Xmx128m -Xms128m'
  protocol: https
  esConfig:
    elasticsearch.yml: |
      cluster.name: "docker-cluster"
      network.host: 0.0.0.0
      xpack.security.enabled: true
      xpack.security.http.ssl.enabled: true
      xpack.security.transport.ssl.enabled: true
      xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch-master.key
      xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch-master.crt
      xpack.security.http.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/ca/ca.crt
      xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch-master.key
      xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch-master.crt
      xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/ca/ca.crt
      # xpack.security.authc.token.enabled: true
      # xpack.security.authc.token.timeout: 20m
  extraEnvs:
    - name: ELASTIC_USERNAME
      valueFrom:
        secretKeyRef:
          name: elasticsearch-password
          key: username
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elasticsearch-password
          key: password
  secretMounts:
    - name: ca-keys
      secretName: ca-keys
      path: /usr/share/elasticsearch/config/certs/ca
    - name: elasticsearch-keys
      secretName: elasticsearch-keys
      path: /usr/share/elasticsearch/config/certs/elasticsearch
  resources:
    requests:
      cpu: 25m
      memory: 256Mi
    # limits:
    #   cpu: 200m
    #   memory: 512Gi

kibana:
  enabled: true
  elasticsearchHosts: https://elasticsearch-master.app.svc.cluster.local:9200
  protocol: https
  kibanaConfig:
    kibana.yml: |
      server.ssl:
        enabled: true
        key: /usr/share/kibana/config/certs/kibana/kibana.key
        certificate: /usr/share/kibana/config/certs/kibana/kibana.crt
      xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
      xpack.reporting.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
      xpack.encryptedSavedObjects.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
      elasticsearch.ssl:
        certificateAuthorities: /usr/share/kibana/config/certs/ca/ca.crt
        verificationMode: certificate
  extraEnvs:
    - name: ELASTICSEARCH_USERNAME
      valueFrom:
        secretKeyRef:
          name: elasticsearch-password
          key: username
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elasticsearch-password
          key: password
    - name: KIBANA_ENCRYPTION_KEY
      valueFrom:
        secretKeyRef:
          name: kibana-keys
          key: encryptionKey
  secretMounts:
    - name: ca-keys
      secretName: ca-keys
      path: /usr/share/kibana/config/certs/ca
    - name: kibana-keys
      secretName: kibana-keys
      path: /usr/share/kibana/config/certs/kibana
  resources:
    requests:
      cpu: 25m
      memory: 256Mi
    # limits:
    #   cpu: 200m
    #   memory: 512Mi