apiVersion: v2
name: helm
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
  - name: jaeger
    version: 0.34.1
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger.enabled