apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-password
type: Opaque
data:
  username: {{ .Values.global.secrets.elasticsearch.username | b64enc }}
  password: {{ .Values.global.secrets.elasticsearch.password | b64enc }}