apiVersion: v1
kind: Secret
metadata:
  name: kibana-keys
type: Opaque
data:
  {{- (.Files.Glob "keys/kibana/*").AsSecrets | nindent 2 }}
  encryptionKey: {{ .Values.global.secrets.kibana.encryptionKey | b64enc }}
    