version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: secret42
        port: 4466
        databases:
          default:
            connector: mysql
            migrations: true
            host: mysql
            port: 3306
            user: root
            password: secret42
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.20
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret42
      - MYSQL_DATABASE=xxx
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret42
    ports:
      - "3306:3306"