version: "3"

services:
  sonic:
    image: valeriansaliou/sonic:v1.3.0
    restart: on-failure
    ports:
      - 1491:1491
    volumes:
      - ./config.cfg:/etc/sonic.cfg
      - ./store/:/var/lib/sonic/store/