apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: deployment-backup
spec:
  repository:
    name: s3-repo
  schedule: "*/5 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: mysql
    volumeMounts:
    - name: data
      mountPath: /var/lib/mysql
    paths:
    - /var/lib/mysql
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
  runtimeSettings:
    container:
      securityContext:
        runAsUser: 999
        runAsGroup: 999