apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: s3-repo
spec:
  backend:
    s3:
      endpoint: http://minio.minio.svc:9000
      bucket: stash
      prefix: /backup/demo/deployment/stash
    storageSecretName: s3-secret